name: wawamko
description: wawamko cliente

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+5

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.8
  http: ^0.13.5
  google_maps_flutter: ^2.0.11
  geocoding: ^2.0.1
  location: ^4.3.0
  page_transition: ^2.0.4
  package_info: ^2.0.2
  animated_background: ^2.0.0
  flutter_html: ^3.0.0-alpha.6
  connectivity: ^3.0.6
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.0
  spring_button: ^2.0.0
  image_picker: ^0.8.4+2
  image_cropper: ^3.0.1
  mime_type: ^1.0.0
  permission_handler: ^10.2.0
  url_launcher: ^6.0.12
  flutter_slidable: ^2.0.0
  webview_flutter: ^4.0.2
  carousel_slider: ^4.0.0
  dots_indicator: ^2.0.0
  animate_do: ^3.0.2
  another_flushbar: ^1.10.24
  shimmer: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0
  provider: ^6.0.0
  mask_text_input_formatter: ^2.0.0
  encrypt: ^5.0.1
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.1.6
  flutter_spinkit: ^5.1.0
  pin_code_fields: ^7.3.0
  #google_maps_place_picker: ^2.1.0-nullsafety.3
  google_sign_in: ^5.4.3
  #flutter_facebook_login: ^3.0.0
  #flutter_facebook_auth: ^3.3.3-no-nullsafety
  flutter_login_facebook: ^1.6.0
  lottie: ^2.2.0
  simple_animations: ^5.0.0+3
  pull_to_refresh: ^2.0.0
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  share: ^2.0.4
  smooth_page_indicator: ^1.0.0+2
  photo_view: ^0.14.0
  file_picker: ^5.2.5
  socket_io_client: ^1.0.1
  sign_in_with_apple: ^4.3.0
  youtube_player_iframe: ^4.0.1
  flutter_google_places: ^0.3.0
  flutter_local_notifications: ^13.0.0
  uni_links: ^0.5.1
  flutter_math_fork: ^0.6.3+1
  flutter_inappwebview: ^5.7.2+3



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  collection: ^1.15.0-nullsafety.4


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FontRegular
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: FontMedium
      fonts:
        - asset: fonts/Roboto-Medium.ttf
    - family: FontBold
      fonts:
        - asset: fonts/Roboto-Bold.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
